spring.datasource.url=jdbc:postgresql://localhost:5432/getgo_e2e
spring.datasource.username=postgres
spring.datasource.password=staza

spring.jpa.hibernate.ddl-auto=create-drop

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
